global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # -------------------------------
  # 1) Prometheus self-monitoring
  # -------------------------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # -------------------------------
  # 2) Node Exporter (métricas del sistema de la máquina)
  # -------------------------------
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # -------------------------------
  # 3) Backend Django
  #    SOLO FUNCIONA si usas django-prometheus
  # -------------------------------
  - job_name: "backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
