name: Run Django Tests and Allure Reports

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django allure-pytest coverage

      - name: Run Django tests with coverage
        run: |
          export DJANGO_SETTINGS_MODULE=NovaBack.settings
          coverage run manage.py test
          coverage xml -o tests/results/coverage.xml

      - name: Download and unzip Allure
        run: |
          mkdir -p allure
          wget -O allure.zip https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
          unzip allure.zip -d allure
          export PATH=$PATH:$(pwd)/allure/allure-2.35.1/bin
          allure --version  # Verifica que se instal√≥ correctamente

      - name: Run pytest with Allure
        run: |
          export DJANGO_SETTINGS_MODULE=NovaBack.settings
          export PATH=$PATH:$(pwd)/allure/allure-2.35.1/bin
          pytest NovaBack --alluredir=tests/results/allure_raw

      - name: Generate Allure Report
        run: |
          export PATH=$PATH:$(pwd)/allure/allure-2.35.1/bin
          allure generate tests/results/allure_raw --clean -o tests/results/allure
